# Generated by Django 4.1.2 on 2022-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_author_rating_author_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='project.PostCategory', to='project.category', verbose_name='Категория '),
        ),
    ]
